import { useNavigation } from '@react-navigation/native';
import React from 'react';
import { View, Text, TextInput, StyleSheet, Image, TouchableOpacity, FlatList } from 'react-native'; // Import de FlatList ajouté
import Animated, { Easing } from 'react-native-reanimated';

const MathScreen = () => {
  const navigation = useNavigation();
  const data = [
    {
      id: '1',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2024',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://drive.google.com/file/d/19CDZ7fqcnB_uZdyYZ4no--m6fsVxobhw/preview?usp=sharing',
    },
    {
      id: '2',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2024',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://drive.google.com/file/d/18wQ70rVuJ083bDJjpzohvqSliCVW8WJD/preview?usp=sharing',
    },
    {
      id: '3',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2024',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '4',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2023',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '5',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2023',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '6',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2023',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '7',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2022',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '8',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2022',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '9',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2022',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '10',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2021',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '11',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2021',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '12',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2021',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '13',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2020',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '14',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2020',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '15',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2020',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '16',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2019',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '17',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2019',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '18',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2019',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '19',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2018',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '20',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2018',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '21',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2018',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '22',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2017',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '23',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2017',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '24',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2017',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '25',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2016',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '26',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2016',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '27',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2016',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '28',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2015',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '29',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2015',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '30',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2015',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '31',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2014',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '32',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2014',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '33',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2014',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '34',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2013',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '35',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2013',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '36',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2013',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '37',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2012',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '38',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2012',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '39',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2012',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '40',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2011',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '41',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2011',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '42',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2011',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '43',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2010',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '44',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2010',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '45',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2010',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '46',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2009',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '47',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2009',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '48',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2009',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '49',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2008',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '50',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2008',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '51',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2008',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '52',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2007',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '53',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2007',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '54',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2007',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '55',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2006',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '56',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2006',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '57',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2006',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '58',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2005',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '59',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2005',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '60',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2005',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '61',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2004',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '62',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2004',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '63',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2004',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '64',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2003',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '65',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2003',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '66',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2003',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '67',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2002',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '68',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2002',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '69',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2002',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '70',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2001',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '71',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2001',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '72',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2001',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '73',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2000',
      time: '4 heures',
      description: 'BAC A',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '74',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2000',
      time: '4 heures',
      description: 'BAC D',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
    {
      id: '75',
      image: require('../assets/math.jpeg'),
      name: 'Epreuves Mathématques 2000',
      time: '4 heures',
      description: 'BAC C',
      corrected: true,
      free: false,
      documentUrl: 'https://example.com/document1.pdf',
    },
  ];

  
  const renderCourseItem = ({ item }) => (
    <TouchableOpacity
      style={styles.courseItem}
      onPress={() => navigation.navigate('PdfViewer', { documentUrl: item.documentUrl })} // Passer documentUrl comme paramètre
    >
      <View style={styles.imageContainer}>
        <Image source={item.image} style={styles.image} />
      </View>
      <View style={styles.contentContainer}>
        <Text style={styles.courseName}>{item.name}</Text>
        <Text style={styles.details}>{item.time} | {item.description}</Text>
        <View style={styles.optionsContainer}>
          {item.corrected && <Text style={styles.option}>Corrigé</Text>}
          {!item.free && <Text style={styles.option}>Gratuit</Text>}
        </View>
      </View>
    </TouchableOpacity>
  );

  return (
    <View style={styles.container}>
      <View style={styles.searchContainer}>
        <TextInput
          style={styles.searchInput}
          placeholder="Rechercher un cours"
          placeholderTextColor="#999"
        />
      </View>
      <Text style={styles.sectionTitle}>Cours disponibles</Text>
      <FlatList
        data={data}
        renderItem={renderCourseItem}
        keyExtractor={item => item.id}
        contentContainerStyle={{ paddingBottom: 20 }}
      />
    </View>
  );
};


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  searchContainer: {
    marginBottom: 20,
  },
  searchInput: {
    height: 40,
    backgroundColor: '#f0f0f5',
    paddingHorizontal: 10,
    borderRadius: 8,
    fontSize: 16,
    color: '#333',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  courseItem: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  imageContainer: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  contentContainer: {
    flex: 1,
    padding: 10,
  },
  courseName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  details: {
    color: '#666',
    marginBottom: 5,
  },
  optionsContainer: {
    flexDirection: 'row',
  },
  option: {
    marginRight: 10,
    color: '#007bff',
    fontWeight: 'bold',
  },
});

export default MathScreen;